jwt:
  secretKey: khdvnkdmfh847rvhfjdcfh874ikrujfchiux34tnkhxfkasdnkasjn
server:
  port:
    8081
spring:


  #api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302, http://google.com
            - name: LoggingOrderFilter
            - name: Authentication
              args:
                isEnabled: false
#            - name: Authorization
#              args:
#                allowedRoles: ADMIN, USER


        #
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Gaurav
            - name: Authentication


